### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by mmahalwy** [eea/eea.docker.varnish#4]
```
syslog service cannot be started: [Errno 13] Permission denied: '/dev/log'
command service cannot be started: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/add_backends.py", line 147, in <module>
    index=index
KeyError: 'director'
system startup cancelled due to error: setup.service failed on start-up with result '<ProcStatus exit_status=1>'
Request made to kill system.
```

**Comment by avoinea** [comment]
The actual error here is `KeyError: 'director'` and it's fixed now.

The `Permission denied` error is just because the container starts with dedicated user instead of root. But this doesn't affect the image functionality, it just doesn't use syslog for logging.

Please also pin version when using in production. The latest tag is not a stable one.
